print('\nDesafio relacionado ao curso de Python do Curso em Vídeo')
print('------------------------------------------------------------')
print('Autor: Marcos Oliveira')
print('Desafio: 001')
print('Aula: Curso Python #04 - Primeiros comandos em Python3')
print('------------------------------------------------------------')
print('Carregando o programa...')
print('Programa iniciado com sucesso')
print('------------------------------------------------------------')

nome = input('Digite seu nome: ')
print('Olá, humano! Então você se chama', nome,'? Seja muito bem vindo ao nosso sistema')
