print('\nDesafio relacionado ao curso de Python do Curso em Vídeo')
print('------------------------------------------------------------')
print('Autor: Marcos Oliveira')
print('Desafio: 002')
print('Aula: Curso Python #04 - Primeiros comandos em Python3')
print('------------------------------------------------------------')
print('Carregando o programa...')
print('Programa iniciado com sucesso')
print('------------------------------------------------------------')

dia = input('Digite o dia de seu nascimento ')
mes = input('Digite o mês de seu nascimento (Ex: Mar para Março)')
ano = input('Digite o ano de seu nascimento (Ex: 1995) ')

print('Você nasceu no dia', dia,'de',mes,'de',ano,'. Correto?')
